name=input("enter your name")
print(name.isalpha())
print(name.isnumeric())
print(name.isalnum())
print(name.islower())
print(name.isupper())
print(name.istitle())
print(name.isnumeric())
print(name.isdigit())
print(name.isascii())